### ISSUE TITLE
Fail Test in should not be able to update repository likes manually

### ISSUE THREAD

**Issue by viniciusflores** [rocketseat-education/bootcamp-gostack-desafios#17]
A descrição da funcionalidade testada no desafio [desafio-conceitos-nodejs](https://github.com/Rocketseat/bootcamp-gostack-desafios/tree/master/desafio-conceitos-nodejs) é: 

> Para que esse teste passe, você não deve permitir que sua rota de update altere diretamente os likes desse repositório, mantendo o mesmo número de likes que o repositório já possuia antes da atualização. Isso porque o único lugar que deve atualizar essa informação é a rota responsável por aumentar o número de likes.

Porém o teste não valida se é mantida a quantidade original de likes do repositório após atualização.

**Comment by TiagoCunhaF** [comment]
@viniciusflores , o teste pede para que seja incrementado o número de likes, e o mesmo teste à partir de um novo repositório (que é iniciado com 0), se após dar like retornará 1. Entendo que esta correto.

Talvez o que você esteja apontando é que se retorna 1 para um repositório que já tivesse 2 likes, o teste seria passado, mas isso é outra coisa / outro teste, esse teste parte de um novo reposiório.

**Comment by josepholiveira** [comment]
Fala @viniciusflores !

Essa funcionalidade é testada sim, mas ela é testada em um outro teste.

https://github.com/Rocketseat/gostack-template-conceitos-nodejs/blob/11d7a7ff5656b6a49f2900d584bed297193f70d3/src/__tests__/repositories.spec.js#L79

Se quiser dar uma olhada está bem nessa linha que eu mandei.

Se ainda tiver alguma dúvida, pode reabrir essa issue. Um abraço!
