### ISSUE TITLE
Desafio 07: GoFinances Web: Erro na validação

### ISSUE THREAD

**Issue by DuarteJD** [rocketseat-education/bootcamp-gostack-desafios#20]
## should be able to upload a file 
Em ambiente windows realmente é necessário alterar o _components/upload/index.ts_ de **text/csv** para **application/vnd.ms-excel**

Porém o teste falha se deixar com esta alteração.
Portanto para a aplicação funcionar no windows precisa realizar a alteração, mas para entregar o desafio sem erros, precisa desafazer a alteração.

**Comment by josepholiveira** [comment]
Faala @DuarteJD !

Para isso não é necessário alterar, você pode apenas adicionar uma vírgula depois e adicionar esse tipo.

Fizemos algumas alterações lá no desafio que já deve funcionar agora.

Um abraço!
