### ISSUE TITLE
Tornar este repositório um Template

### ISSUE THREAD

**Issue by cassioalmeron** [rocketseat-education/bootcamp-gostack-desafios#74]
Marcar este repositório como um template, da mesma forma que os repositórios dos desafios anteriores.

**Comment by josepholiveira** [comment]
Fala @cassioalmeron , tudo bem?

Como esse aqui é apenas o repositório dos enunciados dos desafios, não tem necessidade de marcar ele como um template, visto que não é um modelo :purple_heart: 

Estarei fechando essa issue, mas qualquer dúvida fique a vontade para mandar aqui!

**Comment by cassioalmeron** [comment]
Olá @josepholiveira.

Obrigado!
